enum ActionConstants {
  CREATE_DEFAULT_USER_UI = 'CREATE_DEFAULT_USER_UI',
  ADD_BRIDGE_STATUS_THRESHOLD = 'ADD_BRIDGE_STATUS_THRESHOLD',
  DEL_BRIDGE_EVENT = 'DEL_BRIDGE_EVENT',
  ADD_BRIDGE_EVENT = 'ADD_BRIDGE_EVENT',
  CLEAR_BRIDGES = 'CLEAR_BRIDGES',
  FETCH_BRIDGES_SUCCESS = 'FETCH_BRIDGES_SUCCESS',
  FETCH_UI_SUCCESS = 'FETCH_UI_SUCCESS',
}

export default ActionConstants
